<?php

class SilkException extends Exception {
// implements ChainOfCommandPattern 
// OK So I don't have a clue why I was doing the below.
// I think I had a great idea regarding using some pattern
// with exception handling, but now I have no clue what it was.
// maybe it'll come to me again later.
// Pretend this isn't here.

/*private $next = null;

public __construct($message = '', $code) {
    parent::__construct($message, $code);
}

// ChainOfCommandPattern methods
public get_next() {
    return $this->next;
}

public function set_next($parentException) {
    $this->next = $parentException
}


// shortcut methods for clarity
public function set_parent($parentException) {
    $this->set_next($parentException);
}


public function get_parent() {
    return $this->get_next();
}
*/
}

?>
